[package]
name = "backend"
version = "0.0.1"
edition = "2024"

[features]
dev = []

[dependencies]
axum = { version = "0.8.4" }
axum-reverse-proxy = { version = "1.0.3" }
dotenvy = "0.15.7"
http = "1.3.1"
mime_guess = "2.0.5"
minijinja = { version = "2.12.0", features = ["loader"] }
path-clean = "1.0.1"
reqwest = "0.12.23"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["macros", "net", "rt-multi-thread", "signal"] }
tower-http = { version = "0.6.6", features = ["compression-full", "fs", "trace"] }
tower-livereload = { version = "0.9.6" }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
